
services:
  db:
    container_name: "marketplace-db"
    image: postgres:latest
    restart: always
    volumes:
      - ./.docker/postgresql.conf:/etc/postgresql/postgresql.conf
    environment:
      POSTGRES_PASSWORD:  ${DB_PASS}
      POSTGRES_USER:  ${DB_USER}
      POSTGRES_DB:  ${DB_NAME}
    ports:
      - ${BD_PORT}:5432

  app:
    container_name: 'marketplace-back-end'
    build:
        dockerfile: Dockerfile
    env_file:
      - ./.env
    command: npm run dev
    ports:
      - '80:80'
    depends_on:
      - db
