version: '3.8'

services:
  bff-api:
    build: .
    container_name: bff-isaude
    restart: unless-stopped
    # Carrega as variáveis do arquivo .env
    env_file: .env 
    # REMOVIDO: environment section (para não sobrescrever o .env)
    ports:
      - "8080:80"
    volumes:
      - .:/src
      - /src/node_modules
    command: npm run dev